# Window configuration
[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 1, y = 1 }
opacity = 0.9
decorations = "None"
startup_mode = "Maximized"
# Font configuration
[font]
size = 10.5
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
# Tokyo Night-inspired color scheme
[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"
[colors.normal]
black   = "#32344a"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#ad8ee6"
cyan    = "#449dab"
white   = "#787c99"
[colors.bright]
black   = "#444b6a"
red     = "#ff7a93"
green   = "#b9f27c"
yellow  = "#ff9e64"
blue    = "#7da6ff"
magenta = "#bb9af7"
cyan    = "#0db9d7"
white   = "#acb0d0"
# Cursor style
#[cursor]
#style = { shape = "Block", blinking = "On" }
#unfocused_hollow = true
# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"
# Additional interesting features
[scrolling]
history = 10000
multiplier = 3
[selection]
save_to_clipboard = true
[mouse]
hide_when_typing = true
[bell]
animation = "EaseOutExpo"
duration = 0
# Better performance settings
[debug]
render_timer = false
persistent_logging = false
